on:
    push:
        branches:
            - develop
jobs:
    development:
        name: development
        runs-on: ubuntu-latest
        steps:
            - name: chekout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: build
              run: echo "Build"
            - name: unit test
              run: echo "unit test" 
            - name: static analysis
              run: echo "static analysis"